apiVersion: phylake.io/v1alpha1
kind: Application
metadata:
  name: demo-app
spec:
  applicationOwner: phylake-demo
  securityLevel: internal
  stages:
    - name: foo
      cluster:
        repository: https://github.com/phylake-io/cluster-template.git
        name: single-cluster
      resources:
        path: cluster/namespaces/foo
      targetNamespace: foo
    - name: bar
      cluster:
        repository: https://github.com/phylake-io/cluster-template.git
        name: single-cluster
      resources:
        path: cluster/namespaces/bar
      targetNamespace: bar
      previousStage: foo
