apiVersion: phylake.io/v1alpha1
kind: Application
metadata:
  name: policies
spec:
  stages:
    - name: policies
      cluster:
        repository: https://github.com/phylake-io/cluster-template.git
        name: single-cluster
      resources:
        path: cluster/global/policies
