apiVersion: securitytower.io/v1alpha1
kind: Application
metadata:
  name: namespaces
spec:
  stages:
    - name: namespaces
      cluster:
        repository: https://github.com/securitytower/cluster-template.git
        name: single-cluster
      resources:
        path: cluster/global/namespace-specs
